Measure:
  List:
      - id: 1
        name: Temperature
        order: 1
        allow: true
        unitOfMeasurementIn: '*C'
        unitOfMeasurementOut: '*C'
        convertTo: '*C,F'
        delta: 0.1
      - id: 2
        name: Pressure
        order: 2
        allow: true
        unitOfMeasurementIn: Pa
        unitOfMeasurementOut: mmHg
        convertTo: Pa,mmHg
        delta: 1
      - id: 3
        name: Altitude
        order: 3
        allow: true
        unitOfMeasurementIn: m
        unitOfMeasurementOut: m
        convertTo: m
        delta: 1
      - id: 4
        name: Real altitude
        order: 4
        allow: false
        unitOfMeasurementIn: m
        unitOfMeasurementOut: m
        convertTo: m
        delta: 1
toUi:
    '*C': °C
    'Pa': Pa
    'F': F
    'mmHg': mmHg
    'm': m
transformValue:
    '*C*C': 1
    '*CF': 1
    'PammHg': 0.0075006375541921
    'PaPa': 1
    'mm': 1

