INSERT INTO TYPE_MEASURE (TYPE_MEASURE_NAME) VALUES ('Temperature');
INSERT INTO TYPE_MEASURE (TYPE_MEASURE_NAME) VALUES ('Pressure');
INSERT INTO TYPE_MEASURE (TYPE_MEASURE_NAME) VALUES ('Altitude');
INSERT INTO TYPE_MEASURE (TYPE_MEASURE_NAME) VALUES ('Real altitude');